### ISSUE TITLE
Error with converting NSMBW Japan VC to .iso

### ISSUE THREAD

**Issue by mariomadproductions** [sabykos/nfs2iso2nfs#5]
```
C:\Writ-App\Game Editing Tools\Nintendo - Nintendo Wii U\~General\JNUS\New Super Mario Bros. Wii [VAFJ01]\content>nfs2iso -wiikey wii-common-key.bin

+++++ NFS2ISO +++++

You haven't specified if you want to use nfs2iso or iso2nfs
Found .nfs files! Assuming you want to use nfs2iso...
Searching for AES key file...
AES key file found!
Wii common key not found in source code. Looking for file...
Wii Common Key file found!
Looking for .nfs files...
2 .nfs files found!
Joining .nfs files...

Processing hif_000000.nfs...
Processing hif_000001.nfs...

Decrypting hif.nfs...

256 MB processed...

Unpacking nfs...

5 parts found...
Writing zero segment 0 of size 0x0
Writing data segment 0 of size 0x8000
Writing zero segment 1 of size 0x38000
Writing data segment 1 of size 0x10000
Writing zero segment 2 of size 0xf7b0000
Writing data segment 2 of size 0xe618000
Writing zero segment 3 of size 0x18000
Writing data segment 3 of size 0x1580000
Writing zero segment 4 of size 0x8000
Writing data segment 4 of size 0x59e0000

Read partition table...

Number of 1. partitions: 1
Partition info table offset: 0x40020
Number of 2. partitions: 0
Partition info table offset: 0x0
Number of 3. partitions: 0
Partition info table offset: 0x0
Number of 4. partitions: 0
Partition info table offset: 0x0

Data partition at offset: 0xf800000

Partition size: 0x15580000
Write game partition 0...
256 MB processed...
A Cryptographic error occurred: Specified initialization vector (IV) does not match the block size for this algorithm.

Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: buffer
   at System.IO.BinaryWriter.Write(Byte[] buffer)
   at nfs2iso2nfs.Program.manipulateISO(String InFile, String OutFile, Boolean enc)
   at nfs2iso2nfs.Program.Main(String[] args)

C:\Writ-App\Game Editing Tools\Nintendo - Nintendo Wii U\~General\JNUS\New Super Mario Bros. Wii [VAFJ01]\content`
```
Despite the error, the program did produce an ISO that works in Dolphin.

**Comment by piratesephiroth** [comment]
The releases here haven't been updated and don't work as expected.
Either compile the source yourself or download it from gbatemp.
